apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: quack-db-data
  name: quack-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi